# Generated by YIHSUAN603/Helm .github/workflows/update-homebrew-cask.yml.
# Edit the template there, not this file - the next release overwrites it.
cask "helm-terminal" do
  arch arm: "aarch64", intel: "x64"

  version "0.18.2"
  sha256 arm:   "71c88fac3070c733bc8acc65dbf00e909a43e36c0c666561bfee3e47b1ee3ed9",
         intel: "11d3a3de2ea413c95159928cf283f297a307c21208a9dfba1567ccc1c85fce6e"

  url "https://github.com/YIHSUAN603/Helm/releases/download/v#{version}/Helm_#{version}_#{arch}.dmg"
  name "Helm"
  desc "Terminal that watches your AI coding agents"
  homepage "https://github.com/YIHSUAN603/Helm"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on macos: :catalina

  app "Helm.app"

  # Ad-hoc signed, not notarized: clear the quarantine flag Homebrew
  # sets, or macOS reports the app as damaged. Homebrew 6 removed the
  # --no-quarantine flag, so the cask has to do it.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Helm.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.arieschao.helm",
    "~/Library/Caches/com.arieschao.helm",
    "~/Library/HTTPStorages/com.arieschao.helm",
    "~/Library/Preferences/com.arieschao.helm.plist",
    "~/Library/Saved Application State/com.arieschao.helm.savedState",
    "~/Library/WebKit/com.arieschao.helm",
  ]
end
